### ISSUE TITLE
semantic-ui, etc. ?

### ISSUE THREAD

**Issue by rcarter** [TAPevents/tap-i18n-ui#1]
Are you planning on supporting other UIs as well as Bootstrap? (i.e. Semantic-ui)...

**Comment by rcarter** [comment]
in the meantime, I threw together a package together relying on this for Semantic-UI if anyone else is interested...

https://atmospherejs.com/robinecarter/tap-i18n-semantic-ui

**Comment by IstoraMandiri** [comment]
Hi @rcarter, thanks for the suggestion. We don't have immediate plans to implement this, but I am going to be giving i18n-ui some more love within the next month.

I'm probably going to add multi-framework support, so we can call something like:

```
{{> i18n_buttons framework='foundation'}}
```

In the meantime, thanks for creating that package; I may find those those templates useful in the next version.

Thanks!

**Comment by rcarter** [comment]
I had started an implementation just like that and was gonna send a PR, but didn't know what direction you were gonna take it, so I bailed on it. And then I decided to move the package to my organization namespace on atmosphere, but atmosphere apparently didn't like that, so it currently "set-unmigrated"! gonna try to sort that today.

anyways, the github repo is now at https://github.com/studio127/tap-i18n-semantic-ui if it's useful...

r

**Comment by IstoraMandiri** [comment]
Thinking about it, I prefer the following API

```
{{> i18n_buttons_semantic}}
{{> i18n_buttons_foundation}}
```

Bootstrap remains default, but this would be a pretty easy way to extend for other frameworks, and doesn't require any extra code (other than the template itself). Would totally accept a PR with this implementation. Otherwise I'll probably do something like this myself in the coming month.

**Comment by rcarter** [comment]
sounds good. I might bang something out on this today and send you a PR.

**Comment by rcarter** [comment]
PR: https://github.com/TAPevents/tap-i18n-ui/pull/2

**Comment by IstoraMandiri** [comment]
Thanks for the PR, I have merged & published it and re-organised the folder structure to facilitate future frameworks.

Cheers!
