### ISSUE TITLE
How can I just use selected langueages with i18n_dropdown?

### ISSUE THREAD

**Issue by dalareo** [TAPevents/tap-i18n-ui#12]
I am using

```
{{> i18n_dropdown}}
```

in my custom menu in order to allow users to change app language but it gives me all the languages available. In Telescope these languages are a lot!!! How could I just give the user the option to choose between two languages: spanish and english?
Thanks.

**Comment by IstoraMandiri** [comment]
You need to edit `project-tap.i18n` enabled languages.
